version: "3.7"

# 컴퓨터들
services:
  # 컴퓨터이름
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./services/email.js:/myfolder/services/email.js
      - ./services/phone.js:/myfolder/services/phone.js
      - ./services/token.js:/myfolder/services/token.js
      - ./services/scrapping.js:/myfolder/services/scrapping.js
    ports:
      - 4000:4000

  # 컴퓨터이름
  my-database:
    image: mongo:5
    ports:
      - 27017:27017
